### PR TITLE
Added power support for the travis.yml file with ppc64le. and update go versions for package: httpfs

### PR DESCRIPTION
**Pull request by sreekanth370**
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le.
This helps us simplify testing later when distributions are re-building and re-releasing.

updated the go version go:1.13, 1.14 and 1.15

### CODE REVIEW

**Comment by sreekanth370** [comment]
kindly respond and merge the code with power architecture. For more info tag @gerrith3

**Comment by dmitshur** [comment]
Thanks for the pull request. I am not seeing changes that I'd like to pull into this repository at this time.

> updated the go version go:1.13, 1.14 and 1.15

The current configuration specifies Go "1.x", which matches the latest stable Go release (Go 1.15.5 at this moment), and doesn't require manual updates every 6 months. Supporting older Go versions is out of scope per the [SLA](https://github.com/shurcooL/SLA#go-version) covering this package.

I don't understand the motivation for wanting to test package in this repository on the ppc64le architecture at this time. These packages do not include any architecture-specific code, so the benefit (ability to spot architecture-specific regressions) doesn't seem to justify the cost of running tests twice.

**Comment by sreekanth370** [comment]
updated the go 1.x with amd64 and power support architecture(ppc64le).
 kindly review the same

**Comment by sreekanth370** [comment]
kindly review  and merge the code with power support architecture

**Comment by dmitshur** [comment]
I said earlier:

> I don't understand the motivation for wanting to test package in this repository on the ppc64le architecture at this time. These packages do not include any architecture-specific code, so the benefit (ability to spot architecture-specific regressions) doesn't seem to justify the cost of running tests twice.

Can you please help me understand the motivation? Thanks.

**Comment by sreekanth370** [comment]
the Power architecture - primarily the bigger enterprise class systems from IBM for banking/insurance/retail/etc.etc but this ensures that your code and all dependencies are tested on the Power architecture. Debian/Ubuntu, and Fedora/RHEL/CentOS have ppc64le (Power) distributions and this code goes into those distributions. This ensures that top of tree is always validated on ppc64le using (free) Power servers at Travis CI

**Comment by sreekanth370** [comment]
added the power support on travis.yml and test was succeeded for amd64, ppc64le. kindly merge this transaction for master travis.yml

arch:
amd64
ppc64le

**Comment by sreekanth370** [comment]
Re: github actions - we are planning to add Power hardware there for testing as well, there is a little matter of connecting GHA to a cloud backend right now.

**Comment by dmitshur** [comment]
Closing since the .travis.yml file is deleted as of commit 617b1d4caa554e7fa8edc15c57819043384f2fc5. Thanks.

**Pull request closed without merging**
